"use client";
import './globals.css'
import { SessionProvider } from 'next-auth/react';

export const metadata = {
  title: 'Dashboard App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SessionProvider basePath="/api/auth">
          {children}
        </SessionProvider>
      </body>
    </html>
  )
}
